sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-cssource --build-arg BUILDNODE=TravisCI ./linux
  - docker run -it --rm lacledeslan/gamesvr-cssource ./ll-tests/gamesvr-cssource.s
