sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - docker-ce

git:
  depth: 4

services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-cssource --build-arg BUILDNODE=TravisCI ./linux
  - docker run -it --rm lacledeslan/gamesvr-cssource ./ll-tests/gamesvr-cssource.sh

after_success: |
  echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    if [[ ($TRAVIS_BRANCH == master) && ($TRAVIS_PULL_REQUEST == false) ]] ; then
      curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
      sh trigger-travis.sh lacledeslan gamesvr-cssource-freeplay $TRAVIS_ACCESS_TOKEN
    fi
